### ISSUE TITLE
Voice Button Does Not Send

### ISSUE THREAD

**Issue by puretim** [watson-developer-cloud/simple-chat-objective-c#5]
Successfully compiled and ran the appon my phone. In the app when tapping the mic icon, xcode reads the button tap, but no audio is sent or detected from the mic. All permissions are enabled. Any idea how to handle this?

**Comment by glennrfisher** [comment]
Hi @puretim. Thanks for mentioning the permissions -- I committed a change (b206cf6101447a4e1b5ce55e0cf85a99f829ce03) to make sure that microphone permissions are enabled in the repository.

I followed the getting started instructions and was able to transcribe microphone audio on my iPhone. When it works you will see the following information printed about the volume of the microphone:

![image](https://user-images.githubusercontent.com/1957636/27051014-2ca5ed42-4f7a-11e7-8269-5aeecab47535.png)

There are two ideas that come to mind if you're having trouble with the microphone.

1. It's possible that microphone access was disabled for `ChatApp`. The first time the app tries to access the microphone, there will be a dialog asking for permission from the user. If the user chooses not to allow access to the microphone, then the microphone button will not work. Subsequent requests to access the microphone will be denied, instead of producing a new dialog. To re-enable the microphone, Open the Settings app and navigate to "Privacy -> Microphone". Make sure the `ChatApp` slider is enabled.

2. It's possible that the microphone is working, but you are not seeing any transcription results. To see if that's the case, check the console for information about the microphone volume. You may also see a printed error message from the Speech to Text service.

Hope that helps!
